name: Deploy Api To Prod

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: init with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Docker Build And Push
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -f docker/Dockerfile -t tvchat-core .
          docker tag tvchat-core skysrd/tvchat-core
          docker push skysrd/tvchat-core
      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ubuntu
          key: ${{ secrets.KEY}}
          port: 22
          script: |
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker pull skysrd/tvchat-core
            docker-compose build tvchat-core
            docker-compose up -d tvchat-core
