name: Deploy Api To Prod

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: gradle init
        run: gradle init

      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Spring-application build
        run: ./gradlew build

      - name: Docker Build And Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./docker/Dockerfile -t tvchat-core .
          docker tag tvchat-core skysrd/tvchat-core
          docker push skysrd/tvchat-core

      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ubuntu
          key: ${{ secrets.KEY}}
          port: 22
          script: |
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker pull skysrd/tvchat-core
            docker-compose build tvchat-core
            docker-compose up -d tvchat-core
